#!/usr/bin/env bash
# scripts/server-bootstrap.sh — 首次部署 Yasi Words 的服务器侧一键脚本
#
# 用法（在 Ubuntu 22.04+ 服务器上）：
#   curl -fsSL https://raw.githubusercontent.com/meisijiya/IELTS_WORDS/main/scripts/server-bootstrap.sh | sudo bash -s -- yasi-words.example.com
#
# 或本地：
#   sudo bash scripts/server-bootstrap.sh your-domain.example.com
#
# 它会：
#   1. 安装 Docker + nginx + certbot
#   2. 创建 /opt/yasi-words 工作目录
#   3. 克隆代码
#   4. 生成 .env（强密码 + 随机 SESSION_SECRET）
#   5. 配置 nginx 反代
#   6. 申请 Let's Encrypt 证书
#   7. docker compose up -d --build（第一次构建会下载 238MB 音频）
#   8. 打印验证步骤
set -euo pipefail

DOMAIN="${1:-}"
if [ -z "$DOMAIN" ]; then
  echo "用法: $0 <domain>"
  echo "示例: $0 yasi-words.example.com"
  exit 1
fi

ADMIN_USER="${SUDO_USER:-root}"
APP_DIR="/opt/yasi-words"
GITHUB_REPO="https://github.com/meisijiya/IELTS_WORDS.git"
RELEASE_TAG="audio-2026-07-21"

# ─── 1. 系统依赖 ───
echo "[1/8] 安装系统依赖..."
apt-get update -qq
apt-get install -y -qq docker.io docker-compose-plugin nginx certbot python3-certbot-nginx ufw git openssl

# Ensure docker group membership for the admin user (so docker compose works without sudo)
if [ "$ADMIN_USER" != "root" ]; then
  usermod -aG docker "$ADMIN_USER"
fi

# ─── 2. 项目目录 ───
echo "[2/8] 准备 $APP_DIR ..."
mkdir -p "$APP_DIR"
cd "$APP_DIR"

if [ ! -d .git ]; then
  git clone "$GITHUB_REPO" .
else
  git fetch origin main
  git reset --hard origin/main
fi

# ─── 3. 生成 .env ───
echo "[3/8] 生成 .env..."
PG_PASSWORD=$(openssl rand -base64 18 | tr -dc 'A-Za-z0-9' | head -c 20)
ADMIN_PASSWORD=$(openssl rand -base64 18 | tr -dc 'A-Za-z0-9' | head -c 16)
SESSION_SECRET=$(openssl rand -base64 32)

cat > .env <<EOF
# Generated by server-bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# DO NOT COMMIT — gitignored. Back up securely.

# Postgres credentials (internal to docker network)
POSTGRES_USER=yasi
POSTGRES_PASSWORD=${PG_PASSWORD}
POSTGRES_DB=yasi_db

# App
ADMIN_PASSWORD=${ADMIN_PASSWORD}
SESSION_SECRET=${SESSION_SECRET}
APP_PORT=3000
TZ=Asia/Shanghai

# Audio bundle URL — baked into Docker image at build time
AUDIO_BUNDLE_URL=https://github.com/meisijiya/IELTS_WORDS/releases/download/${RELEASE_TAG}/audio.tgz
EOF
chmod 600 .env

# Save admin password to a readable file (one-time)
echo "$ADMIN_PASSWORD" > .admin_password
chmod 600 .admin_password
echo "[!] Admin password saved to $APP_DIR/.admin_password — DELETE AFTER FIRST LOGIN"

# ─── 4. 防火墙 ───
echo "[4/8] 配置防火墙..."
ufw --force reset >/dev/null 2>&1 || true
ufw default deny incoming >/dev/null
ufw default allow outgoing >/dev/null
ufw allow 22/tcp comment "SSH" >/dev/null
ufw allow 80/tcp comment "HTTP (Let's Encrypt)" >/dev/null
ufw allow 443/tcp comment "HTTPS" >/dev/null
# 不要开放 3000 — 仅 nginx 反代访问
ufw --force enable >/dev/null

# ─── 5. nginx 反代 ───
echo "[5/8] 配置 nginx..."
cat > /etc/nginx/sites-available/yasi-words <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN};

    client_max_body_size 10M;

    # Allow Let's Encrypt http-01 challenge
    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 60s;
    }
}
EOF
ln -sf /etc/nginx/sites-available/yasi-words /etc/nginx/sites-enabled/yasi-words
rm -f /etc/nginx/sites-enabled/default
nginx -t
systemctl reload nginx

# ─── 6. Let's Encrypt ───
echo "[6/8] 申请 HTTPS 证书..."
certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos --register-unsafely-without-email || {
  echo "[!] Certbot failed (DNS not pointing yet?). Skipping HTTPS — HTTP only for now."
  echo "    Run 'sudo certbot --nginx -d $DOMAIN' after DNS is configured."
}

# ─── 7. 启动 docker ───
echo "[7/8] docker compose up -d --build (首次构建会下载 238MB 音频，预计 5-10 分钟)..."
docker compose pull postgres || true
docker compose build --build-arg "AUDIO_BUNDLE_URL=https://github.com/meisijiya/IELTS_WORDS/releases/download/${RELEASE_TAG}/audio.tgz" app
docker compose up -d

# ─── 8. 健康检查 ───
echo "[8/8] 等待应用启动..."
for i in 1 2 3 4 5 6 7 8 9 10; do
  if curl -fsS http://127.0.0.1:3000/login >/dev/null 2>&1; then
    echo "[health] OK — 应用已就绪"
    break
  fi
  echo "[health] 等待中 ($i/10)..."
  sleep 5
done

echo ""
echo "════════════════════════════════════════════════════════════"
echo " 部署完成！"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "访问:    https://${DOMAIN}/"
echo "登录密码（首次登录后删除）: $(cat .admin_password)"
echo ""
echo "验证清单："
echo "  docker compose ps                          # 容器状态"
echo "  docker compose logs --tail=50 app          # 应用日志"
echo "  curl -fsS https://${DOMAIN}/login         # 外部健康"
echo ""
echo "GitHub Actions 自动部署还需要："
echo "  1. 在 GitHub repo → Settings → Secrets 配置："
echo "     - ALIYUN_REGISTRY (e.g. registry.cn-hangzhou.aliyuncs.com)"
echo "     - ALIYUN_REGISTRY_NAMESPACE (个人版用户名)"
echo "     - ALIYUN_REGISTRY_USERNAME"
echo "     - ALIYUN_REGISTRY_PASSWORD"
echo "     - DEPLOY_HOST (this server's IP)"
echo "     - DEPLOY_SSH_USER (default: root)"
echo "     - DEPLOY_SSH_KEY (private key, public key in ~/.ssh/authorized_keys)"
echo ""
echo "  2. 上传音频包到 GitHub Release（如未做）："
echo "     gh release create ${RELEASE_TAG} release/audio.tgz \\"
echo "       --repo meisijiya/IELTS_WORDS --title 'audio bundle' --clobber"
echo ""
echo "  3. git push origin main → CI 自动 build + deploy"
echo "════════════════════════════════════════════════════════════"